cabal-version: 3.4
name:          hasksyma
version:       0.1
license:       BSD-3-Clause
license-file:  LICENSE
copyright:     (c) 2023 Drexel University
author:        Geoffrey Mainland <mainland@drexel.edu>
maintainer:    Geoffrey Mainland <mainland@drexel.edu>
stability:     alpha
homepage:      https://github.com/mainland/hasksyma
category:      Language
synopsis:      Symbolic expressions
extra-source-files: .ghci
tested-with:   GHC==9.10.3,
               GHC==9.12.4,
               GHC==9.14.1

description:
  Symbolic expressions.

build-type: Simple

flag cyclotomic
    description: Enable support for cyclotomic numbers
    manual: True
    default: False

flag ihaskell
    description: Enable notebook display support
    manual: True
    default: False

flag partial-evaluation
    description: Enable partial evaluation in Exp instances
    manual: True
    default: True

library
  hs-source-dirs: src
  default-language: Haskell2010

  exposed-modules:
    Hasksyma
    Hasksyma.Const
    Hasksyma.Diff
    Hasksyma.Eval
    Hasksyma.Exp
    Hasksyma.Integrate
    Hasksyma.LaTeX
    Hasksyma.Pretty
    Hasksyma.Simplify

  build-depends:
    base            >= 4.20  && < 4.23,
    containers      >= 0.6   && < 0.9,
    mainland-pretty >= 0.7   && < 0.8,
    symbol          >= 0.2.4 && < 0.3,
    text            >= 1.2   && < 2.2,
    HaTeX           >= 3.21  && < 3.24

  ghc-options:
    -Wall

  if flag(cyclotomic)
    cpp-options: -DCYCLOTOMIC
    build-depends: cyclotomic >= 1.1 && < 1.2

  if flag(partial-evaluation)
    cpp-options: -DPEVAL

library ihaskell
  visibility: public
  hs-source-dirs: ihaskell
  exposed-modules: Hasksyma.IHaskell
  default-language: Haskell2010

  if !flag(ihaskell)
    buildable: False

  -- The released IHaskell dependency requires ghc <9.13.
  if impl(ghc >= 9.13)
    buildable: False

  build-depends:
    base            >= 4.20  && < 4.23,
    hasksyma:hasksyma,
    HaTeX           >= 3.21  && < 3.24,
    ihaskell        >= 0.13  && < 0.14,
    text            >= 1.2   && < 2.2

  ghc-options:
    -Wall

test-suite full
  type: exitcode-stdio-1.0
  main-is: Main.hs
  default-language: Haskell2010
  hs-source-dirs:
    test

  other-modules:
    Test.Arbitrary
    Test.Const
    Test.Diff
    Test.Eval
    Test.Exact
    Test.Integrate
    Test.NoPEval
    Test.PEval
    Test.Simplify

  build-depends:
    hasksyma,
    base            >= 4.20 && < 4.23,
    hspec           >= 2.9  && < 2.12,
    mainland-pretty >= 0.7  && < 0.8,
    HUnit           >= 1.6  && < 1.7,
    QuickCheck      >= 2.13 && < 2.18

  if flag(partial-evaluation)
    cpp-options: -DPEVAL

source-repository head
  type:     git
  location: https://github.com/mainland/hasksyma.git
